theme = "hyde"
relativeURLs = true
baseURL = "/"
title = "Baron Chandler"
author = "Baron Chandler"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true

[params]
  themeColor = "theme-base-77"
  imageURL = "/hat.png"
  titleURL = "/name.svg"
  description = "A personal blog."
  copyright = "Copyright ©2021 Baron Chandler. All Rights Reserved."

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
