# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Site
        run: |
          docker build . -t blog:latest

      - name: Setup SSH keys
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan sargasso.nyc3.venturecranial.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_SSH_KEY }}"

      - name: Push to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          docker save blog:latest | gzip -9 | ssh github@sargasso.nyc3.venturecranial.com zcat \| docker load
          ssh github@sargasso.nyc3.venturecranial.com docker kill blog.baronchandler.com \|\| true \; docker run -it --rm -d -p 8080:80 --name blog.baronchandler.com blog:latest \; docker image prune -af
